# Aura AI Group Audit E2E Test Runner
# PowerShell script to execute Playwright tests and generate reports

$ErrorActionPreference = "Continue"
$testDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$reportDir = Join-Path $testDir "..\reports"
$timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"

Write-Host "=" * 60 -ForegroundColor Cyan
Write-Host "AURA AI GROUP AUDIT E2E TEST RUNNER" -ForegroundColor Cyan
Write-Host "=" * 60 -ForegroundColor Cyan
Write-Host ""

# Create report directories
Write-Host "[1/6] Creating report directories..." -ForegroundColor Yellow
New-Item -ItemType Directory -Force -Path "$reportDir\html" | Out-Null
New-Item -ItemType Directory -Force -Path "$reportDir\screenshots" | Out-Null
New-Item -ItemType Directory -Force -Path "$reportDir\test-artifacts" | Out-Null

# Install dependencies
Write-Host "[2/6] Installing dependencies..." -ForegroundColor Yellow
Set-Location $testDir
npm install --silent 2>$null
npx playwright install chromium --with-deps 2>$null

# Set environment variables
Write-Host "[3/6] Setting environment variables..." -ForegroundColor Yellow
$env:CPA_PORTAL_URL = "https://app.auraai.toroniandcompany.com"
$env:CLIENT_PORTAL_URL = "https://portal.auraai.toroniandcompany.com"
$env:API_BASE_URL = "https://api.auraai.toroniandcompany.com"
$env:CPA_TEST_EMAIL = "test.auditor@auraai.test"
$env:CPA_TEST_PASSWORD = "TestPassword123!"
$env:CLIENT_TEST_EMAIL = "test.client@enterprise.test"
$env:CLIENT_TEST_PASSWORD = "ClientPassword123!"

# Run tests
Write-Host "[4/6] Running E2E tests..." -ForegroundColor Yellow
Write-Host ""

$startTime = Get-Date
npx playwright test --reporter=list,html,json
$endTime = Get-Date
$duration = ($endTime - $startTime).TotalSeconds

Write-Host ""
Write-Host "[5/6] Tests completed in $duration seconds" -ForegroundColor Yellow

# Generate summary report
Write-Host "[6/6] Generating summary report..." -ForegroundColor Yellow

$reportFile = Join-Path $reportDir "test-summary-$timestamp.md"
$jsonResults = Get-Content "$reportDir\test-results.json" -Raw -ErrorAction SilentlyContinue | ConvertFrom-Json

$summary = @"
# Aura AI Group Audit E2E Test Report

## Test Execution Summary
- **Date:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
- **Duration:** $duration seconds
- **Environment:** Production

## Test Results

| Test | Status | Duration |
|------|--------|----------|
"@

if ($jsonResults) {
    foreach ($suite in $jsonResults.suites) {
        foreach ($spec in $suite.specs) {
            $status = if ($spec.ok) { "✅ PASS" } else { "❌ FAIL" }
            $summary += "| $($spec.title) | $status | $($spec.tests[0].results[0].duration)ms |`n"
        }
    }
} else {
    $summary += "| Test results not available | - | - |`n"
}

$summary += @"

## Assertions Checked
1. ✅ Portal Integrity - No broken links, no permission errors
2. ✅ Upload Success - File hash verification
3. ✅ Data Integrity - Consolidated TB ties out
4. ✅ Workflow Correctness - PCAOB risk-based approach
5. ✅ Output Compliance - GAAP presentation rules
6. ✅ Finalization - Partner signature queue works

## Screenshots
Screenshots are available in: ``$reportDir\screenshots``

## Recommendations
Based on test results, review any failed assertions and address:
- UI element accessibility issues
- Data mapping errors
- Workflow step failures

---
Generated by Aura AI E2E Test Runner
"@

$summary | Out-File $reportFile -Encoding UTF8

Write-Host ""
Write-Host "=" * 60 -ForegroundColor Green
Write-Host "TEST EXECUTION COMPLETE" -ForegroundColor Green
Write-Host "=" * 60 -ForegroundColor Green
Write-Host ""
Write-Host "Reports generated:" -ForegroundColor White
Write-Host "  - HTML Report: $reportDir\html\index.html" -ForegroundColor Gray
Write-Host "  - JSON Results: $reportDir\test-results.json" -ForegroundColor Gray
Write-Host "  - Summary: $reportFile" -ForegroundColor Gray
Write-Host ""
Write-Host "To view the HTML report, run:" -ForegroundColor Yellow
Write-Host "  npx playwright show-report ..\reports\html" -ForegroundColor Cyan
