# R&D Study E2E Test Runner
# PowerShell script to execute Playwright tests and generate reports

$ErrorActionPreference = "Continue"
$testDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$reportDir = Join-Path $testDir "..\reports"
$timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"

Write-Host "=" * 60 -ForegroundColor Cyan
Write-Host "R&D STUDY AUTOMATION E2E TEST RUNNER" -ForegroundColor Cyan
Write-Host "Testing PA and NY State Credits" -ForegroundColor Cyan
Write-Host "=" * 60 -ForegroundColor Cyan
Write-Host ""

# Create report directories
Write-Host "[1/6] Creating report directories..." -ForegroundColor Yellow
New-Item -ItemType Directory -Force -Path "$reportDir\html" | Out-Null
New-Item -ItemType Directory -Force -Path "$reportDir\screenshots" | Out-Null
New-Item -ItemType Directory -Force -Path "$reportDir\test-artifacts" | Out-Null

# Install dependencies
Write-Host "[2/6] Installing dependencies..." -ForegroundColor Yellow
Set-Location $testDir
npm install --silent 2>$null
npx playwright install chromium --with-deps 2>$null

# Set environment variables
Write-Host "[3/6] Setting environment variables..." -ForegroundColor Yellow
$env:API_BASE_URL = "https://api.auraai.toroniandcompany.com"
$env:CPA_PORTAL_URL = "https://app.auraai.toroniandcompany.com"
$env:CLIENT_PORTAL_URL = "https://portal.auraai.toroniandcompany.com"
$env:CPA_TEST_EMAIL = "test.auditor@auraai.test"
$env:CPA_TEST_PASSWORD = "TestPassword123!"
$env:CPA_FIRM_ID = "test-firm-id"

# Run tests
Write-Host "[4/6] Running R&D Study E2E tests..." -ForegroundColor Yellow
Write-Host ""

$startTime = Get-Date
npx playwright test --reporter=list,html,json
$endTime = Get-Date
$duration = ($endTime - $startTime).TotalSeconds

Write-Host ""
Write-Host "[5/6] Tests completed in $duration seconds" -ForegroundColor Yellow

# Generate summary report
Write-Host "[6/6] Generating summary report..." -ForegroundColor Yellow

$reportFile = Join-Path $reportDir "rd-study-test-summary-$timestamp.md"
$jsonResults = Get-Content "$reportDir\test-results.json" -Raw -ErrorAction SilentlyContinue | ConvertFrom-Json

$summary = @"
# R&D Study Automation E2E Test Report

## Test Execution Summary
- **Date:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
- **Duration:** $duration seconds
- **Environment:** Production
- **Test Company:** TechNova Solutions Inc.
- **Tax Year:** 2024

## State Credits Tested
- Pennsylvania (PA): 10% credit rate, 15-year carryforward
- New York (NY): 9% credit rate, refundable for QETCs
- California (CA): 24% credit rate
- Texas (TX): 5% franchise tax credit
- New Jersey (NJ): Based on federal methodology

## Test Results

| Test Suite | Status | Duration |
|------------|--------|----------|
"@

if ($jsonResults) {
    foreach ($suite in $jsonResults.suites) {
        foreach ($spec in $suite.specs) {
            $status = if ($spec.ok) { "PASS" } else { "FAIL" }
            $summary += "| $($spec.title) | $status | $($spec.tests[0].results[0].duration)ms |`n"
        }
    }
} else {
    $summary += "| Test results not available | - | - |`n"
}

$summary += @"

## Key Assertions Validated
1. Study Creation - Entity setup with multi-state nexus
2. Document Upload - Payroll, supplies, contract research data
3. QRE Classification - Wages, supplies, contract research by state
4. AI 4-Part Test - Qualification analysis and narrative generation
5. Federal Credit Calculation - Regular and ASC methods
6. PA State Credit - 10% rate calculation with carryforward
7. NY State Credit - 9% rate with refundability check
8. Excel Workbook Generation - Full study workbook download
9. PDF Report Generation - Complete study report download

## Output Files Generated
- Excel Workbook: ``technova_rd_study_2024.xlsx``
- PDF Report: ``technova_rd_study_2024.pdf``

## Recommendations
- Review any failed test cases for root cause analysis
- Verify state credit calculations against manual calculations
- Confirm AI-generated narratives meet documentation standards

---
Generated by R&D Study E2E Test Runner
"@

$summary | Out-File $reportFile -Encoding UTF8

Write-Host ""
Write-Host "=" * 60 -ForegroundColor Green
Write-Host "TEST EXECUTION COMPLETE" -ForegroundColor Green
Write-Host "=" * 60 -ForegroundColor Green
Write-Host ""
Write-Host "Reports generated:" -ForegroundColor White
Write-Host "  - HTML Report: $reportDir\html\index.html" -ForegroundColor Gray
Write-Host "  - JSON Results: $reportDir\test-results.json" -ForegroundColor Gray
Write-Host "  - Summary: $reportFile" -ForegroundColor Gray
Write-Host ""
Write-Host "Output files:" -ForegroundColor White
Write-Host "  - Excel: $reportDir\technova_rd_study_2024.xlsx" -ForegroundColor Gray
Write-Host "  - PDF: $reportDir\technova_rd_study_2024.pdf" -ForegroundColor Gray
Write-Host ""
Write-Host "To view the HTML report, run:" -ForegroundColor Yellow
Write-Host "  npx playwright show-report ..\reports\html" -ForegroundColor Cyan
