/*
 * Migration 011: Advanced Report Generation
 *
 * Adds database tables for:
 * 1. Report templates with constitutional AI principles
 * 2. Generated reports with structured sections
 * 3. Compliance validation history
 * 4. Multi-agent collaboration tracking
 * 5. Self-consistency voting records
 * 6. Citation validation
 *
 * Author: Claude AI
 * Date: 2024
 */

-- ============================================================================
-- 1. REPORT TEMPLATES
-- ============================================================================

-- Report templates with constitutional AI principles
CREATE TABLE IF NOT EXISTS report_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Template metadata
    template_name VARCHAR(100) NOT NULL UNIQUE,
    template_type VARCHAR(50) NOT NULL CHECK (template_type IN ('audit_report', 'review_report', 'compilation_report', 'attestation_report')),
    entity_type VARCHAR(50) NOT NULL CHECK (entity_type IN ('public_company', 'private_company', 'non_profit', 'government')),
    framework VARCHAR(20) NOT NULL CHECK (framework IN ('GAAP', 'IFRS', 'OCBOA')),

    -- Sections configuration
    sections JSONB NOT NULL, -- [{name, required, principles, ...}]

    -- Constitutional AI principles
    constitutional_principles JSONB NOT NULL, -- [{principle_id, principle_name, regulatory_source, ...}]

    -- Applicable standards
    applicable_standards JSONB NOT NULL, -- ["AS_3101", "AU-C_700", ...]

    -- Metadata
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES users(id),
    is_active BOOLEAN DEFAULT TRUE,
    version VARCHAR(20) NOT NULL DEFAULT '1.0'
);

CREATE INDEX idx_report_templates_type ON report_templates(template_type, entity_type);

-- ============================================================================
-- 2. GENERATED REPORTS
-- ============================================================================

-- Audit reports generated by the system
CREATE TABLE IF NOT EXISTS generated_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Report identification
    report_number VARCHAR(50) UNIQUE,
    engagement_id UUID NOT NULL REFERENCES engagements(id),
    template_id UUID NOT NULL REFERENCES report_templates(id),

    -- Report metadata
    report_type VARCHAR(50) NOT NULL,
    entity_name VARCHAR(200) NOT NULL,
    report_date DATE NOT NULL,
    period_end DATE NOT NULL,

    -- Opinion
    opinion_type VARCHAR(50) NOT NULL CHECK (opinion_type IN ('unmodified', 'qualified', 'adverse', 'disclaimer')),
    opinion_text TEXT NOT NULL,

    -- Report sections (structured)
    title TEXT NOT NULL,
    addressee TEXT NOT NULL,
    opinion_section TEXT NOT NULL,
    basis_for_opinion TEXT NOT NULL,
    responsibilities_section TEXT NOT NULL,
    additional_sections JSONB, -- [{section_name, content}, ...]
    signature_section TEXT NOT NULL,

    -- Generation metadata
    generation_method VARCHAR(50) NOT NULL CHECK (generation_method IN ('constitutional_ai', 'multi_agent', 'self_consistency', 'hybrid')),
    agents_used JSONB, -- ["opinion", "basis", "compliance", "editor"]

    -- Model information
    primary_model VARCHAR(100),
    model_version VARCHAR(50),
    total_tokens_used INTEGER,
    generation_time_seconds INTEGER,

    -- Compliance
    compliance_score FLOAT CHECK (compliance_score >= 0 AND compliance_score <= 1),
    compliance_validated BOOLEAN DEFAULT FALSE,
    compliance_validated_at TIMESTAMP,

    -- Status
    status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'review', 'approved', 'issued')),
    approved_by UUID REFERENCES users(id),
    approved_at TIMESTAMP,
    issued_at TIMESTAMP,

    -- Metadata
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES users(id)
);

CREATE INDEX idx_generated_reports_engagement ON generated_reports(engagement_id);
CREATE INDEX idx_generated_reports_status ON generated_reports(status, created_at DESC);
CREATE INDEX idx_generated_reports_date ON generated_reports(report_date DESC);

-- ============================================================================
-- 3. COMPLIANCE VALIDATION
-- ============================================================================

-- Compliance validation results
CREATE TABLE IF NOT EXISTS compliance_validations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    report_id UUID NOT NULL REFERENCES generated_reports(id) ON DELETE CASCADE,

    -- Validation metadata
    validation_type VARCHAR(50) NOT NULL CHECK (validation_type IN ('automated', 'neural', 'hybrid', 'manual')),
    validator_model VARCHAR(100),

    -- Results
    compliant BOOLEAN NOT NULL,
    compliance_score FLOAT NOT NULL CHECK (compliance_score >= 0 AND compliance_score <= 1),

    -- Violations
    total_violations INTEGER NOT NULL DEFAULT 0,
    critical_violations INTEGER NOT NULL DEFAULT 0,
    high_violations INTEGER NOT NULL DEFAULT 0,
    medium_violations INTEGER NOT NULL DEFAULT 0,
    low_violations INTEGER NOT NULL DEFAULT 0,

    -- Detailed violations
    violations JSONB, -- [{rule_id, severity, section, message, suggestion}, ...]

    -- Recommendations
    recommendations JSONB,

    -- Metadata
    validated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validated_by UUID REFERENCES users(id),
    validation_duration_seconds INTEGER
);

CREATE INDEX idx_compliance_validations_report ON compliance_validations(report_id, validated_at DESC);
CREATE INDEX idx_compliance_validations_compliant ON compliance_validations(compliant);

-- Individual compliance rule violations (for analysis)
CREATE TABLE IF NOT EXISTS compliance_violations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    validation_id UUID NOT NULL REFERENCES compliance_validations(id) ON DELETE CASCADE,
    report_id UUID NOT NULL REFERENCES generated_reports(id) ON DELETE CASCADE,

    -- Rule information
    rule_id VARCHAR(50) NOT NULL,
    rule_name VARCHAR(200) NOT NULL,
    regulatory_source VARCHAR(100) NOT NULL, -- "PCAOB AS 3101.08"

    -- Violation details
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')),
    section_name VARCHAR(100),
    violation_text TEXT,
    expected_text TEXT,
    actual_text TEXT,

    -- Remediation
    suggestion TEXT NOT NULL,
    auto_fixable BOOLEAN DEFAULT FALSE,
    fixed BOOLEAN DEFAULT FALSE,
    fixed_at TIMESTAMP,

    -- Metadata
    detected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_compliance_violations_validation ON compliance_violations(validation_id);
CREATE INDEX idx_compliance_violations_rule ON compliance_violations(rule_id, severity);
CREATE INDEX idx_compliance_violations_severity ON compliance_violations(severity) WHERE fixed = FALSE;

-- ============================================================================
-- 4. MULTI-AGENT COLLABORATION
-- ============================================================================

-- Agent executions for report generation
CREATE TABLE IF NOT EXISTS agent_executions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    report_id UUID NOT NULL REFERENCES generated_reports(id) ON DELETE CASCADE,

    -- Agent information
    agent_name VARCHAR(50) NOT NULL, -- "opinion", "basis", "compliance", "editor"
    agent_role VARCHAR(100) NOT NULL,
    agent_temperature FLOAT NOT NULL,
    agent_model VARCHAR(100) NOT NULL,

    -- Execution
    section_name VARCHAR(100) NOT NULL,
    input_context JSONB NOT NULL,
    output_text TEXT NOT NULL,

    -- Quality metrics
    confidence_score FLOAT,
    tokens_used INTEGER,
    execution_time_seconds INTEGER,

    -- Collaboration
    depends_on_agents JSONB, -- ["opinion", "basis"]
    validated_by_agent VARCHAR(50), -- "compliance"
    validation_passed BOOLEAN,
    validation_feedback TEXT,

    -- Metadata
    executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    execution_order INTEGER NOT NULL -- 1, 2, 3...
);

CREATE INDEX idx_agent_executions_report ON agent_executions(report_id, execution_order);
CREATE INDEX idx_agent_executions_agent ON agent_executions(agent_name, executed_at DESC);

-- ============================================================================
-- 5. SELF-CONSISTENCY VOTING
-- ============================================================================

-- Self-consistency samples and voting
CREATE TABLE IF NOT EXISTS self_consistency_samples (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    report_id UUID NOT NULL REFERENCES generated_reports(id) ON DELETE CASCADE,
    section_name VARCHAR(100) NOT NULL,

    -- Sample generation
    sample_number INTEGER NOT NULL, -- 1-5
    temperature FLOAT NOT NULL,
    seed INTEGER,

    -- Generated text
    sample_text TEXT NOT NULL,

    -- Extracted decisions
    key_decisions JSONB NOT NULL, -- [{decision_type, decision_value}, ...]

    -- Voting
    selected BOOLEAN DEFAULT FALSE,
    selection_reason TEXT,

    -- Metadata
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tokens_used INTEGER
);

CREATE INDEX idx_self_consistency_samples ON self_consistency_samples(report_id, section_name, sample_number);

-- Voting results
CREATE TABLE IF NOT EXISTS self_consistency_votes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    report_id UUID NOT NULL REFERENCES generated_reports(id) ON DELETE CASCADE,
    section_name VARCHAR(100) NOT NULL,

    -- Decision being voted on
    decision_type VARCHAR(100) NOT NULL, -- "opinion_type", "going_concern", etc.

    -- Vote counts
    total_samples INTEGER NOT NULL,
    decision_values JSONB NOT NULL, -- [{value, count, percentage}, ...]

    -- Consensus
    consensus_reached BOOLEAN NOT NULL,
    consensus_value TEXT,
    consensus_percentage FLOAT,

    -- Final decision
    final_decision TEXT NOT NULL,
    decision_confidence FLOAT NOT NULL,

    -- Metadata
    voted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_self_consistency_votes ON self_consistency_votes(report_id, section_name);

-- ============================================================================
-- 6. CITATIONS AND REFERENCES
-- ============================================================================

-- Citations in generated reports
CREATE TABLE IF NOT EXISTS report_citations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    report_id UUID NOT NULL REFERENCES generated_reports(id) ON DELETE CASCADE,

    -- Citation details
    citation_type VARCHAR(50) NOT NULL CHECK (citation_type IN ('work_paper', 'pcaob_standard', 'aicpa_standard', 'asc_topic', 'sec_regulation')),
    citation_text VARCHAR(200) NOT NULL, -- "[AS 3101.08]"

    -- Parsed information
    standard_id VARCHAR(50), -- "AS_3101"
    paragraph VARCHAR(20), -- "08"

    -- Context
    section_name VARCHAR(100) NOT NULL,
    surrounding_text TEXT,

    -- Validation
    validated BOOLEAN DEFAULT FALSE,
    validation_status VARCHAR(50), -- "valid", "invalid", "superseded", "not_found"
    validation_message TEXT,
    superseded_by VARCHAR(50),

    -- Metadata
    extracted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_report_citations_report ON report_citations(report_id, section_name);
CREATE INDEX idx_report_citations_type ON report_citations(citation_type, validated);
CREATE INDEX idx_report_citations_standard ON report_citations(standard_id);

-- ============================================================================
-- 7. CONSTITUTIONAL AI PRINCIPLES TRACKING
-- ============================================================================

-- Track adherence to constitutional AI principles
CREATE TABLE IF NOT EXISTS constitutional_principle_adherence (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    report_id UUID NOT NULL REFERENCES generated_reports(id) ON DELETE CASCADE,
    section_name VARCHAR(100) NOT NULL,

    -- Principle
    principle_id VARCHAR(50) NOT NULL, -- "AS_3101_P1"
    principle_name VARCHAR(200) NOT NULL,
    regulatory_source VARCHAR(100) NOT NULL,

    -- Adherence
    adheres BOOLEAN NOT NULL,
    confidence FLOAT CHECK (confidence >= 0 AND confidence <= 1),

    -- Evidence
    evidence_text TEXT,
    violation_example TEXT,

    -- Refinement
    required_refinement BOOLEAN DEFAULT FALSE,
    refinement_count INTEGER DEFAULT 0,

    -- Metadata
    checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_constitutional_adherence ON constitutional_principle_adherence(report_id, section_name, adheres);
CREATE INDEX idx_constitutional_principle ON constitutional_principle_adherence(principle_id, adheres);

-- ============================================================================
-- 8. REPORT FEEDBACK AND CONTINUOUS IMPROVEMENT
-- ============================================================================

-- CPA feedback on generated reports
CREATE TABLE IF NOT EXISTS report_feedback (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    report_id UUID NOT NULL REFERENCES generated_reports(id),

    -- Feedback source
    user_id UUID NOT NULL REFERENCES users(id),
    user_role VARCHAR(20) NOT NULL,

    -- Overall rating
    overall_rating INTEGER CHECK (overall_rating >= 1 AND overall_rating <= 5),

    -- Specific ratings
    accuracy_rating INTEGER CHECK (accuracy_rating >= 1 AND accuracy_rating <= 5),
    completeness_rating INTEGER CHECK (completeness_rating >= 1 AND completeness_rating <= 5),
    compliance_rating INTEGER CHECK (compliance_rating >= 1 AND compliance_rating <= 5),
    clarity_rating INTEGER CHECK (clarity_rating >= 1 AND clarity_rating <= 5),

    -- Detailed feedback
    strengths TEXT,
    weaknesses TEXT,
    suggestions TEXT,

    -- Specific issues
    compliance_issues JSONB, -- [{section, issue, severity}, ...]
    factual_errors JSONB,

    -- Edits made
    sections_edited JSONB, -- [{section, before, after, reason}, ...]
    total_edits INTEGER DEFAULT 0,

    -- Time saved
    estimated_time_saved_minutes INTEGER,
    would_use_again BOOLEAN,

    -- Metadata
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_report_feedback_report ON report_feedback(report_id);
CREATE INDEX idx_report_feedback_rating ON report_feedback(overall_rating, created_at DESC);

-- ============================================================================
-- 9. PERFORMANCE METRICS
-- ============================================================================

-- Aggregate metrics for monitoring
CREATE TABLE IF NOT EXISTS report_generation_metrics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Time period
    date DATE NOT NULL,
    report_type VARCHAR(50) NOT NULL,

    -- Volume
    total_reports_generated INTEGER NOT NULL DEFAULT 0,
    reports_approved INTEGER NOT NULL DEFAULT 0,
    reports_issued INTEGER NOT NULL DEFAULT 0,

    -- Quality
    avg_compliance_score FLOAT,
    avg_generation_time_seconds INTEGER,
    avg_tokens_used INTEGER,

    -- Compliance
    reports_with_critical_violations INTEGER DEFAULT 0,
    avg_violations_per_report FLOAT,

    -- Feedback
    avg_overall_rating FLOAT,
    avg_accuracy_rating FLOAT,
    avg_time_saved_minutes INTEGER,

    -- Efficiency
    total_time_saved_hours FLOAT,
    total_cost_saved_usd FLOAT,

    UNIQUE(date, report_type)
);

CREATE INDEX idx_report_gen_metrics_date ON report_generation_metrics(date DESC);

-- ============================================================================
-- MATERIALIZED VIEWS
-- ============================================================================

-- Daily compliance violations summary
CREATE MATERIALIZED VIEW IF NOT EXISTS mv_daily_compliance_violations AS
SELECT
    DATE(cv.detected_at) as date,
    cv.rule_id,
    cv.rule_name,
    cv.regulatory_source,
    cv.severity,
    COUNT(*) as violation_count,
    SUM(CASE WHEN cv.fixed THEN 1 ELSE 0 END) as fixed_count,
    SUM(CASE WHEN cv.auto_fixable THEN 1 ELSE 0 END) as auto_fixable_count
FROM compliance_violations cv
GROUP BY DATE(cv.detected_at), cv.rule_id, cv.rule_name, cv.regulatory_source, cv.severity;

CREATE UNIQUE INDEX idx_mv_daily_compliance_viol ON mv_daily_compliance_violations(date, rule_id, severity);

-- Agent performance summary
CREATE MATERIALIZED VIEW IF NOT EXISTS mv_agent_performance AS
SELECT
    ae.agent_name,
    COUNT(*) as total_executions,
    AVG(ae.confidence_score) as avg_confidence,
    AVG(ae.execution_time_seconds) as avg_execution_time,
    AVG(ae.tokens_used) as avg_tokens,
    SUM(CASE WHEN ae.validation_passed THEN 1 ELSE 0 END) as validations_passed,
    CAST(SUM(CASE WHEN ae.validation_passed THEN 1 ELSE 0 END) AS FLOAT) / NULLIF(COUNT(*), 0) as pass_rate
FROM agent_executions ae
WHERE ae.executed_at >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY ae.agent_name;

CREATE UNIQUE INDEX idx_mv_agent_perf ON mv_agent_performance(agent_name);

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- Function to refresh materialized views (call daily)
CREATE OR REPLACE FUNCTION refresh_report_generation_metrics() RETURNS void AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_daily_compliance_violations;
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_agent_performance;
END;
$$ LANGUAGE plpgsql;

-- Function to update report status
CREATE OR REPLACE FUNCTION update_report_status()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_report_timestamp
BEFORE UPDATE ON generated_reports
FOR EACH ROW
EXECUTE FUNCTION update_report_status();

-- Function to calculate compliance score
CREATE OR REPLACE FUNCTION calculate_compliance_score(
    p_critical_count INTEGER,
    p_high_count INTEGER,
    p_medium_count INTEGER,
    p_low_count INTEGER
) RETURNS FLOAT AS $$
DECLARE
    v_total_weight FLOAT;
    v_max_weight FLOAT := 100.0;
BEGIN
    -- Weighted scoring: CRITICAL=10, HIGH=5, MEDIUM=2, LOW=1
    v_total_weight := (p_critical_count * 10.0) +
                      (p_high_count * 5.0) +
                      (p_medium_count * 2.0) +
                      (p_low_count * 1.0);

    -- Return score (0-1)
    RETURN GREATEST(0.0, 1.0 - (v_total_weight / v_max_weight));
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE report_templates IS 'Report templates with constitutional AI principles';
COMMENT ON TABLE generated_reports IS 'AI-generated audit reports with structured sections';
COMMENT ON TABLE compliance_validations IS 'Automated compliance validation results';
COMMENT ON TABLE compliance_violations IS 'Individual compliance rule violations';
COMMENT ON TABLE agent_executions IS 'Multi-agent collaboration tracking for report generation';
COMMENT ON TABLE self_consistency_samples IS 'Self-consistency samples for voting';
COMMENT ON TABLE self_consistency_votes IS 'Voting results from self-consistency';
COMMENT ON TABLE report_citations IS 'Citations extracted from generated reports';
COMMENT ON TABLE constitutional_principle_adherence IS 'Adherence to constitutional AI principles';
COMMENT ON TABLE report_feedback IS 'CPA feedback on generated reports';
COMMENT ON TABLE report_generation_metrics IS 'Aggregate performance metrics';

-- ============================================================================
-- GRANTS
-- ============================================================================

-- Grant appropriate permissions
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO atlas;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO atlas;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO atlas;
